### ISSUE TITLE
Data is old, not updating properly  

### ISSUE THREAD

**Issue by knightfury16** [KhanShaheb34/nCov19-InteractiveDashboard-BD#8]
Data is not properly updating probably due to the fact that they again changed the distribution form of data.

**Comment by ahmedsadman** [comment]
@KhanShaheb34 The issue was from the API and it's fixed. You can close it now. By the way, please add the last updated portion both in stats and districts. It helps a lot. An improvement would be to convert the time in UTC +6. That is very doable from the frontend. If not possible manually, then consider looking into moments.js

**Comment by KhanShaheb34** [comment]
@ahmedsadman, Ok I'm adding last update time.

**Comment by KhanShaheb34** [comment]
I added the last update time for both stat and district data
